/* 🤖 this file was generated by svg-to-ts*/
export const iconList: {
  name: 'list'
  data: string
} = {
  name: 'list',
  data: `<svg fill="none" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24"><path xmlns="http://www.w3.org/2000/svg" d="M4 7a1 1 0 011-1h1a1 1 0 010 2H5a1 1 0 01-1-1zm5 0a1 1 0 011-1h9a1 1 0 110 2h-9a1 1 0 01-1-1zm-5 5a1 1 0 011-1h1a1 1 0 110 2H5a1 1 0 01-1-1zm5 0a1 1 0 011-1h9a1 1 0 110 2h-9a1 1 0 01-1-1zm-5 5a1 1 0 011-1h1a1 1 0 110 2H5a1 1 0 01-1-1zm5 0a1 1 0 011-1h9a1 1 0 110 2h-9a1 1 0 01-1-1z" fill="#0D0D0D"/></svg>`,
}
